python3 main.py \
  --run_name "test_reflexion" \
  --root_dir "root" \
  --dataset_path ./benchmarks/humaneval-rs.jsonl \
  --strategy "reflexion" \
  --language "rs" \
  --model "llama3.3-70b-instruct-fp8" \
  --base_url "https://api.lambda.ai/v1" \
  --pass_at_k "1" \
  --max_iters "2" \
  --verbose
